#!/usr/bin/env python3
"""
Seed script — creates 3 default users for the axis.edzlms.com frontend.

Run once after migration 008:
    cd /home/axisai/axisai-backend/axis-ai
    source .venv/bin/activate
    python scripts/seed_users.py

Output: /home/axisai/backend/AXIS_CREDENTIALS.txt (chmod 600 automatically)

Users created:
  admin@axis.edzlms.com   → role: admin
  creator@axis.edzlms.com → role: creator
  learner@axis.edzlms.com → role: learner

Passwords are randomly generated and written to CREDENTIALS file.
Run this script only ONCE. It is idempotent (won't duplicate if run again).
"""
import asyncio
import os
import secrets
import stat
import sys
import uuid
from pathlib import Path

# Add parent dir to path so we can import app modules
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.config import settings
from app.core.database import AsyncSessionFactory
from app.core.jwt import hash_password
from app.models.user import AxisUser
from sqlalchemy import select

CREDENTIALS_FILE = Path("/home/proteek11/axisai/backend/AXIS_CREDENTIALS.txt")

MASTER_TENANT_ID = uuid.UUID("00000000-0000-0000-0000-000000000000")


def generate_password(length: int = 16) -> str:
    """Generate a secure random password."""
    alphabet = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$"
    return "".join(secrets.choice(alphabet) for _ in range(length))


async def seed() -> None:
    users_to_create = [
        {
            "email": "admin2@axis.edzlms.com",
            "full_name": "Axis Admin",
            "role": "admin",
        },
        {
            "email": "creator2@axis.edzlms.com",
            "full_name": "Content Creator",
            "role": "creator",
        },
        {
            "email": "learner2@axis.edzlms.com",
            "full_name": "Demo Learner",
            "role": "learner",
        },
    ]

    credentials = []

    async with AsyncSessionFactory() as session:
        for user_data in users_to_create:
            # Check if already exists
            result = await session.execute(
                select(AxisUser).where(AxisUser.email == user_data["email"])
            )
            existing = result.scalar_one_or_none()

            if existing:
                print(f"  [SKIP] {user_data['email']} already exists")
                credentials.append({
                    "email": user_data["email"],
                    "password": "(already existed — check original credentials file)",
                    "role": user_data["role"],
                })
                continue

            password = generate_password()
            user = AxisUser(
                id=uuid.uuid4(),
                tenant_id=MASTER_TENANT_ID,
                email=user_data["email"],
                password_hash=hash_password(password),
                full_name=user_data["full_name"],
                role=user_data["role"],
                is_active=True,
            )
            session.add(user)
            print(f"  [CREATE] {user_data['email']} ({user_data['role']})")
            credentials.append({
                "email": user_data["email"],
                "password": password,
                "role": user_data["role"],
            })

        await session.commit()

    # Write credentials file
    lines = [
        "=" * 60,
        "axis.edzlms.com — Default User Credentials",
        "Generated by scripts/seed_users.py",
        "=" * 60,
        "",
        "IMPORTANT: Store these credentials securely.",
        "Change passwords after first login via the admin panel.",
        "",
    ]
    for c in credentials:
        lines.append(f"Role:     {c['role']}")
        lines.append(f"Email:    {c['email']}")
        lines.append(f"Password: {c['password']}")
        lines.append("")

    lines.extend([
        "=" * 60,
        "Login URL: https://axis.edzlms.com/login",
        "=" * 60,
    ])

    content = "\n".join(lines)
    CREDENTIALS_FILE.write_text(content)
    # Restrict to owner only (chmod 600)
    CREDENTIALS_FILE.chmod(stat.S_IRUSR | stat.S_IWUSR)

    print(f"\nCredentials written to: {CREDENTIALS_FILE}")
    print("\n" + content)


if __name__ == "__main__":
    print("Seeding axis.edzlms.com users...\n")
    asyncio.run(seed())
    print("\nDone.")
